apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-counter-files
  namespace: traffic-counter
  labels:
    app.kubernetes.io/name: traffic-counter
    app.kubernetes.io/part-of: traffic-counter
data:
  ignore.txt: |-
    # Example prefixes to ignore
    10.0.0.0/8
    192.168.0.0/16
  accept.txt: |-
    # Example prefixes explicitly accepted
    203.0.113.0/24
    2001:db8::/32
