apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-counter
  namespace: traffic-counter
  labels:
    app.kubernetes.io/name: traffic-counter
    app.kubernetes.io/part-of: traffic-counter
