[package]
name = "traffic-counter-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
aya-ebpf = { workspace = true }
traffic-counter-common = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "traffic-counter"
path = "src/main.rs"